<?php
return array (
  6 => 
  array (
    'catid' => '6',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '6,7,8,9',
    'catname' => '收集信息',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'data',
    'url' => 'http://data.csc86.com/index.php?m=content&c=index&a=lists&catid=6',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '6',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'shoujixinxi',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  7 => 
  array (
    'catid' => '7',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '6',
    'arrparentid' => '0,6',
    'child' => '0',
    'arrchildid' => '7',
    'catname' => '纺织',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'data/',
    'catdir' => 'textile',
    'url' => 'http://data.csc86.com/index.php?m=content&c=index&a=lists&catid=7',
    'items' => '30',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '7',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'fangzhi',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  8 => 
  array (
    'catid' => '8',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '6',
    'arrparentid' => '0,6',
    'child' => '0',
    'arrchildid' => '8',
    'catname' => '橡胶',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'data/',
    'catdir' => 'plastic',
    'url' => 'http://data.csc86.com/index.php?m=content&c=index&a=lists&catid=8',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '8',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xiangjiao',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '6',
    'arrparentid' => '0,6',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => '包装',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'data/',
    'catdir' => 'package',
    'url' => 'http://data.csc86.com/index.php?m=content&c=index&a=lists&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'default\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'baozhuang',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>